### PR TITLE
Add Event Overlay Support

### PR DESCRIPTION
**Pull request by cory-stripe**
We have a PR out for the Yelp version, but in the meantime we can add it here.

This adds event overlay support.

r? @sjung-stripe

### CODE REVIEW

**Comment by sjung-stripe** [comment]
the functionality looks good to me, but could we update the [doc](https://github.com/stripe/terraform-provider-signalform/blob/stripe/master/docs/resources/dashboard.md) as well? this is a fairly complex nested structure and could use an example

**Comment by cory-stripe** [comment]
Oh, derp. I couldn't find those docs. Thanks!

**Comment by cory-stripe** [comment]
Docs added @sjung-stripe. Back atcha!

**Comment by sjung-stripe** [comment]
lgtm

**Pull request merged**
